name: React

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4

#      - name: Set up Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v4
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'npm'

      - name: npm ci
      - run: npm ci

      - name: Build
        run: npm run build --prefix ./client

#      - name: Test
#        run: npm test --prefix ./client
